sudo: required
language: java
jdk:
- openjdk11
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_2d494be9a77e_key -iv $encrypted_2d494be9a77e_iv
  -in travis/helseci.key.enc -out travis/helseci.key -d
- git clone https://github.com/navikt/github-apps-support.git
- export PATH=`pwd`/github-apps-support/bin:$PATH
- export GH_TOKEN=$(generate-installation-token.sh `generate-jwt.sh ./travis/helseci.key
  $GITHUB_APP_ID`)
- export COMMIT_SHORT=$(git rev-parse --short HEAD)
- echo -e "machine api.github.com login x-access-token password $GH_TOKEN" > ~/.netrc
script:
- "./gradlew build && docker build --pull -t $DOCKER_IMG_NAME:$COMMIT_SHORT ."
- |
   set -e
   if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then
     echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
     docker push $DOCKER_IMG_NAME:$COMMIT_SHORT

     PREPROD_NAISERATOR=$(docker run -v ${PWD}:/workdir mikefarah/yq yq r nais-preprod.yaml -j)
     PREPROD_NAISERATOR=$(echo $PREPROD_NAISERATOR | jq '.spec.image = "'$DOCKER_IMG_NAME':'$COMMIT_SHORT'"' -c)

     PREPROD_DEPLOYMENT=$(cat deployment.json | jq '.payload.kubernetes.resources += ['$PREPROD_NAISERATOR']')
     PREPROD_DEPLOYMENT=$(echo $PREPROD_DEPLOYMENT | jq '.environment = "dev-fss"')
     PREPROD_DEPLOYMENT=$(echo $PREPROD_DEPLOYMENT | jq '.ref = "'$COMMIT_SHORT'"')

     curl -i -n \
       -X POST \
       -d "$PREPROD_DEPLOYMENT" \
       -H "Accept: application/vnd.github.ant-man-preview+json" \
       https://api.github.com/repos/navikt/helse-spade/deployments

     PROD_NAISERATOR=$(docker run -v ${PWD}:/workdir mikefarah/yq yq r nais-prod.yaml -j)
     PROD_NAISERATOR=$(echo $PROD_NAISERATOR | jq '.spec.image = "'$DOCKER_IMG_NAME':'$COMMIT_SHORT'"' -c)

     PROD_DEPLOYMENT=$(cat deployment.json | jq '.payload.kubernetes.resources += ['$PROD_NAISERATOR']')
     PROD_DEPLOYMENT=$(echo $PROD_DEPLOYMENT | jq '.environment = "prod-fss"')
     PROD_DEPLOYMENT=$(echo $PROD_DEPLOYMENT | jq '.ref = "'$COMMIT_SHORT'"')

     curl -i -n \
       -X POST \
       -d "$PROD_DEPLOYMENT" \
       -H "Accept: application/vnd.github.ant-man-preview+json" \
       https://api.github.com/repos/navikt/helse-spade/deployments
   fi
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - APP_NAME=spade
  - DOCKER_IMG_NAME=navikt/spade
  - GITHUB_APP_ID=19726
  - secure: OgmKASuu7eaX3HlmQ9nKnVjIvHPxrMTmrJwzuBtl8IT/onqQ2E4Y4u1EKgerz8Klk7OcvnIHads52MZ8K6eci8YoR3+lmFq6knadd+QOua3fqZ7/WxwXgq3GAgn1gp+pQ2zAiF+6u8o41pRZjz6L4nPiHE3ulBmKsqDgzE4NDP+zA3lrUqdPcrK8HGpHlOnBmqpBMDWS5eLDHOgPkvoQf0QQ9ZXptz1vC/AHVxz5NZoBDMDB/Y8lM+UXGQJiBWJjxyNVX6du2mhv+LIpl+9/+w7iZjHbMyK8sqqqI7SCcnO3RMo4Bz8DiJtCoVjlcohexHwjGCr/oRWDMHTXW/qpagDwaVfP5EIhQbvvtjMEgZQjv3RS/ICcIxQFcw8Ysf9Wz7kRvygvsfFYZx5P0bItz0mMIqSca/+a1GkcFeJ241cEy+Ue6rK1X//Wg7D9TZfEzzMbQm1/dZoBXSAYRURfHMQWQcj9cvqafxe2fpOGvxMtc8Kc1uIr38ES81/PEb6XxDJCvAvVQDgx2gtArD678U2EeTNdR3d0iSnbb140n9aKlxBl83vrTvycQRIBHt0/VIMtZnpOhW+XaA1kclPDX9jwIHfTq2YdsfVhBb67yfT5Au8GJndQpOvVRIreHA1ZfK9c6irtmMBjJXqXflXU/7C4A/bOad8WhSCiGPTRU6Y=
  - secure: C7s4jG1TXO+RlaLSxk31HZCbaXgHifFfqRe8ozmgNepEO0N2NoeQeay+OMAhJBc8ZKvqjQu/l1DVFzDK04C6/T8sMByoaY3uzAuGlAZE1qdO2/WUx0eJ3CyIsJS4nsk6jyL8bhuE9o0GHE1AhTHlQjKp+JGsIexij2SbKM1ZvSO8wnyLfzP8lY+QCMeG+xGcDKiaEQG9bEgbhosFqpzgwYbkNVW5yqm8443xn5yuCIfwQp8XSDEMRwh9IF41QK/2zUEGxwsuX/RRCub5962/pSyuxb3j7z50UbKwpRqyOYrRgcdmoJqvakHxy8eaeWW2E70DffuBHmtW5lMTQTd9KAi2MLI7zxfQkj9yIV/H+K1dSATH0pNOSNMTM7mliuNe9USe3IRGAXQLDDy7yPjXwsd9lV6NX82WysHF1JaOzU3Go/TXlLi2O7YrAlv4iSd5zpnCyvojagciDXuZj+AP+2djqAm4lZXjmnM6j8s8h5FK65KcdqHsCKHEKWkOdc73uO/N7lqvhR/3s2WoVBJdhzxGzk1zmBjvqQ6XCt+hZP2eqikVGivn+Yr7hYlOMWRJkWAd86UmFmGnDUvtEJm3V8ngHzzVxmE7ewK+XdFc61f7P2AWNa5Wr21s7uctWzsFl3+kLtzDuzUoA+EoevHDi50Pc91ZY2ASE2pTIcSXygE=
notifications:
  slack:
    secure: o6456mWUuxONQqFP7QX8AF/HOusizWt0Y4d08eSLsruDcQY0HbM5dKgha8KEEdMHKZPlrGdSBG1WS1YfnnnJBUWLSiAppvmd4paGiTzPxjDUAeWJwV3Tq16qGKCsjtp+vB2kLwcnm564jQCTmYbZyGGK5GK/q+E2rbZ3x3ooBRZBNjEnr56Let+kkBMj8sJZ7sS+VPkLfKHtTuzLEl3BgUrdF31lHerJ3QtSeEisBVHk95AhmMYJnoiEXCIdYLbgp/I5hkAe936PnREWyc3Rw+Ek3dLJ9mNvN7uczenqOQjUx0KvTneQEAekBafjBJUzJn/0qnBRABe0IDNe2b7bs1hOUdeQsN20HovLDNw2jzWq7nuQ5tN8C+g6lcsRVuHJNKHZ8uC+LSBx1hFzom1a9ecXgp+qa9Kv+gwSgwNPBsc5898+HsLg6+Pr9Yw7Nc8tXxYZKMddJn3imBMQroJWX/f64Pf6EY24gc8BTOgvWLX7TBmFsIW09cA56DfRqc/vqovAkbF0uiKSn88qu7K1UKJD2hzrDhASN68jrYSmBBDSNc5IhFumuVaWZ+RVdHPhKyEZbmbajxH93Lh174Wi6xI4/BnJa/cUxAXCPO4dkfSpTp8ZB5JRzEZfiru7u9mJT1UkvFarvYixxZcisT1k00runpJ6VFiqhUy4pxK4Ot4=
