version: '3.2'
services:
   oidc:
      image: qlik/simple-oidc-provider
      container_name: simple-oidc-provider
      ports:
        - 9000:9000
      networks:
         default:
            aliases:
               - simple-oidc-provider
      volumes:
        - './oidc-users.json:/oidc-users.json'
        - './oidc-config.json:/oidc-config.json'
      environment:
         - REDIRECTS=http://localhost:3000/callback
         - USERS_FILE=/oidc-users.json
         - CONFIG_FILE=/oidc-config.json
   spade:
      image: navikt/spade:local
      container_name: spade
      ports:
        - 8083:8083
      environment:
         - REQUIRED_GROUP=spadegruppe
         - KAFKA_BOOTSTRAP_SERVERS=kafka:19020
         - OIDC_CONFIG_URL=http://simple-oidc-provider:9000/.well-known/openid-configuration
         - CLIENT_ID=foo
         - CLIENT_SECRET=bar
         - SERVICEUSER_USERNAME=spadekafkauser
         - SERVICEUSER_PASSWORD=spadekafkapassword
      depends_on:
        - oidc
        - kafka
   kafka:
      image: confluentinc/cp-kafka:5.1.0
      networks:
         default:
            aliases:
               - kafka
      environment:
         - KAFKA_ADVERTISED_LISTENERS=LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
         - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
         - KAFKA_INTER_BROKER_LISTENER_NAME= LISTENER_DOCKER_INTERNAL
         - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
         - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      ports:
         - "9092:9092"
      depends_on:
         - zookeeper
   zookeeper:
      image: confluentinc/cp-zookeeper:5.1.0
      environment:
         - ZOOKEEPER_CLIENT_PORT=2181
      ports:
         - "2181:2181"
