apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
   name: spade
   namespace: default
   labels:
      team: tbd
spec:
   image: is_set_from_pipeline
   port: 8080
   team: tbd
   liveness:
      path: isalive
      initialDelay: 20
      timeout: 1
      periodSeconds: 5
      failureThreshold: 10
   readiness:
      path: isready
      initialDelay: 20
      timeout: 1
   resources:
      limits:
         cpu: 2000m
         memory: 512Mi
      requests:
         cpu: 50m
         memory: 128Mi
   ingresses:
      - https://spade.nais.adeo.no
   replicas:
      min: 1
      max: 1
      cpuThresholdPercentage: 90
   prometheus:
      enabled: true
      path: /metrics
   secrets: true
   env:
      - name: KAFKA_BOOTSTRAP_SERVERS
        value: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443
      - name: OIDC_CONFIG_URL
        value: https://login.microsoftonline.com/common/.well-known/openid-configuration

