apiVersion: nais.io/v1alpha1
kind: Application
metadata:
   name: {{app}}
   namespace: default
   labels:
      team: {{team}}
spec:
   image: {{image}}:{{tag}}
   port: 8080
   team: tbd
   liveness:
      path: isalive
      initialDelay: 20
      timeout: 1
      periodSeconds: 5
      failureThreshold: 10
   readiness:
      path: isready
      initialDelay: 20
      timeout: 1
   resources:
      limits:
         cpu: 2000m
         memory: 1024Mi
      requests:
         cpu: 100m
         memory: 512Mi
   ingresses:
      - https://spade.nais.adeo.no
   replicas:
      min: 1
      max: 1
      cpuThresholdPercentage: 90
   prometheus:
      enabled: true
      path: /metrics
   vault:
      enabled: true
   webproxy: true
   secureLogs:
      enabled: true
   env:
      - name: KAFKA_BOOTSTRAP_SERVERS
        value: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443

